image: continuumio/miniconda3

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get install libgl1
#  - conda create --name puma -c conda-forge python pip gcc cython numpy scikit-image scipy matplotlib pyevtk pyvista -y
  - conda create -y --name puma -c conda-forge puma
  - conda init bash
  - source ~/.bashrc
  - conda activate puma
  - python -m pip install --upgrade pip
  - python -m pip install pytest
  - python -m  pip install -e .  # install pumapy
  - cd python/test

test:
  script:
    - pytest test_conductivity.py
    - pytest test_filters.py
    - pytest test_generation.py
    - pytest test_io.py
    - pytest test_isosurf_sa_mil_vf_orient.py
    - pytest test_elasticity.py
    - pytest test_permeability.py
    - pytest test_radiation_raycast.py
    - pytest test_segmentation.py
    # - pytest test_texgen_weave.py  # no texgen when using pip install
    - pytest test_workspace.py
    # - pytest test_visualization.py  # failing due to vtk from pip
