image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -m pip install --upgrade pip
  - python -m pip install pytest
  - python -m pip install numpy
  - python -m  pip install -e .  # install pumapy
  - cd python/test

test:
  script:
    - pytest test_conductivity.py
    - pytest test_filters.py
    - pytest test_generation.py
    - pytest test_io.py
    - pytest test_isosurf_sa_mil_vf_orient.py
    - pytest test_mpsa_elasticity.py
    - pytest test_permeability.py
    - pytest test_radiation_raycast.py
    - pytest test_segmentation.py
    # - pytest test_texgen_weave.py  # no texgen when using pip install
    - pytest test_workspace.py
    # - pytest test_visualization.py  # failing due to vtk from pip
