{% set name = "puma" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - cmake >=3.11.0
    - make
    - swig
  host:
    - xorg-libxfixes  # [linux]
    - python
    - pip
    - setuptools
    - numpy
    - eigen
    - fftw
    - libtiff
    - qt
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-image
    - matplotlib
    - pyevtk
    - numpy-stl
    - pyvista
    - fenics-dolfin

test:
  imports:
    - TexGen.Core
    - pumapy
  source_files:
    - python/tests/*.py

about:
  home: https://github.com/nasa/puma
  license: NASA-1.3
  license_file: 
    - LICENSE.txt
    - install/TexGen/LICENSE.txt
    - gui/src/Utilities/qcustomplot/GPL.txt
  summary: 'A package to compute material properties from micro-CT data.'
  description: |
    The Porous Microstructure Analysis (PuMA) software has been developed in order to 
    compute effective material properties and perform material response simulations on 
    digitized microstructures of porous media. PuMA is able to import digital three-dimensional 
    images obtained from X-ray microtomography or to generate artificial microstructures 
    that mimic real materials. PuMA also provides a module for interactive 3D visualizations. 
    Version 3 includes modules to compute simple morphological properties such as porosity, 
    volume fractions, pore diameter, and specific surface area. Additional capabilities include 
    the determination of effective thermal and electrical conductivity (including the ability 
    to simulate local anisotropy), effective diffusivity and tortuosity from the continuum to 
    the rarefied regime, and techniques to determine local material orientation.
  doc_url: https://puma-nasa.readthedocs.io/
  dev_url: https://gitlab.com/jcfergus/puma-dev

extra:
  recipe-maintainers:
    - fsemerar


source:
  url: https://gitlab.com/jcfergus/puma-dev/-/archive/main/puma-dev-main.tar.gz
