name: puma
channels:
  - conda-forge
dependencies:
  - python

  # pumapy
  - numpy
  - scikit-image >=0.17
  - scipy
  - matplotlib
  - pyevtk
  - pyvista

  # puma cpp
  - fftw
  - eigen
  - openmp
  - cmake >=3.11.0 # needed >=3.11.0

  # puma gui
  - qt >=5.9.0 # needed >=5.9.0

  # texgen
  - swig

  # nice to have
  - pip
  - cython
  - scikit-umfpack
  - jupyterlab
  - ipyvtklink
  - ipympl
